stages:
  - test_27
  - test_36


variables:
  POSTGRES_DB: liberapay_tests
  POSTGRES_USER: test_user
  POSTGRES_PASSWORD: test_password
  DATABASE_URL: postgresql://postgres/$POSTGRES_DB?user=$POSTGRES_USER&password=$POSTGRES_PASSWORD

test_27:
  stage: test_27
  image: python:2.7
  services:
    - postgres
  before_script:
    - apt-get update
    - apt-get -y install python-pip postgresql-client
    - pip install tox
    - ./recreate-schema.sh test
  cache:
    paths:
    - .tox
  only:
  - master
  script:
    - tox

test_36:
  stage: test_36
  image: python:3.6
  services:
    - postgres
  before_script:
    - apt-get update
    - apt-get -y install python-tox python3-pip postgresql-client
    - ./recreate-schema.sh test
  cache:
    paths:
    - .tox
  only:
  - master
  script:
    - tox
