language: python
addons:
  postgresql: 9.4
branches:
  only:
    - master
cache:
  directories:
    - .tox
install:
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rf .tox; fi
 - pip install tox
before_script:
 - psql -U postgres -c 'CREATE DATABASE liberapay_tests;'
 - make test-schema
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rfv tests/py/fixtures; export LIBERAPAY_I18N_TEST=yes; fi
script: tox
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#liberapay"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
sudo: false
