language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
addons:
  postgresql: 11
branches:
  only:
    - master
cache:
  directories:
    - .tox
before_install:
 - tar -xaf ../../liberapay-liberapay.com.tar.gz --strip-components=1
install:
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rf .tox; fi
 - pip install tox "six>=1.14.0"
before_script:
 - psql -U postgres -c 'CREATE DATABASE liberapay_tests;'
 - DATABASE_URL=liberapay_tests ./recreate-schema.sh test
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rfv tests/py/fixtures; export LIBERAPAY_I18N_TEST=yes; fi
script: tox
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#liberapay"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
sudo: false
dist: bionic
git:
  strategy: tarball
