version: '2'

services:
    web:
        extends:
            file: docker/common.yml
            service: web
        command: python app.py
        entrypoint: honcho run -e defaults.env,docker/defaults.env,local.env
        links:
            - db
        ports:
            - "8339:8339"

    db:
        image: postgres:9.4
        volumes:
            - /var/lib/postgresql/data
